org: carterh
app: display-html-service
service: display-html-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
